/*
 * @Author       : lqm283
 * @Date         : 2023-01-09 14:01:35
 * @LastEditTime : 2023-01-11 14:15:26
 * @LastEditors  : lqm283
 * --------------------------------------------------------------------------------<
 * @Description  : Please edit a descrition about this file at here.
 * --------------------------------------------------------------------------------<
 * @FilePath     : /jsonc/test/include/double/test_double_json_to_mult.h
 */
#ifndef __TEST_DOUBLE_JSON_TO_MULT_H_
#define __TEST_DOUBLE_JSON_TO_MULT_H_

#include "../obj.h"
#include "test_non_arr_double.h"
#include "test_non_non_double.h"
#include "test_ptr_arr_double.h"
#include "test_ptr_non_double.h"

static const struct TestChangeToMult NonNonDoubleChangeToMult[] = {
    FUNC(test_change_single_str_json_to_non_non_single_double_num),
    FUNC(test_change_mult_str_json_to_non_non_single_double_num),
    FUNC(test_change_single_num_json_to_non_non_single_double_num),
    FUNC(test_change_mult_num_json_to_non_non_single_double_num),
    FUNC(test_change_single_bool_json_to_non_non_single_double_num),
    FUNC(test_change_mult_bool_json_to_non_non_single_double_num),
    FUNC(test_change_single_null_json_to_non_non_single_double_num),
    FUNC(test_change_mult_null_json_to_non_non_single_double_num),
    FUNC(test_change_single_str_json_to_non_non_single_double_bool),
    FUNC(test_change_mult_str_json_to_non_non_single_double_bool),
    FUNC(test_change_single_num_json_to_non_non_single_double_bool),
    FUNC(test_change_mult_num_json_to_non_non_single_double_bool),
    FUNC(test_change_single_bool_json_to_non_non_single_double_bool),
    FUNC(test_change_mult_bool_json_to_non_non_single_double_bool),
    FUNC(test_change_single_null_json_to_non_non_single_double_bool),
    FUNC(test_change_mult_null_json_to_non_non_single_double_bool),
    FUNC(test_change_equal_mult_str_json_to_non_non_mult_double_num),
    FUNC(test_change_more_mult_str_json_to_non_non_mult_double_num),
    FUNC(test_change_less_mult_str_json_to_non_non_mult_double_num),
    FUNC(test_change_diff_mult_str_json_to_non_non_mult_double_num),
    FUNC(test_change_equal_mult_num_json_to_non_non_mult_double_num),
    FUNC(test_change_more_mult_num_json_to_non_non_mult_double_num),
    FUNC(test_change_less_mult_num_json_to_non_non_mult_double_num),
    FUNC(test_change_diff_mult_num_json_to_non_non_mult_double_num),
    FUNC(test_change_equal_mult_bool_json_to_non_non_mult_double_num),
    FUNC(test_change_more_mult_bool_json_to_non_non_mult_double_num),
    FUNC(test_change_less_mult_bool_json_to_non_non_mult_double_num),
    FUNC(test_change_diff_mult_bool_json_to_non_non_mult_double_num),
    FUNC(test_change_equal_mult_null_json_to_non_non_mult_double_num),
    FUNC(test_change_more_mult_null_json_to_non_non_mult_double_num),
    FUNC(test_change_less_mult_null_json_to_non_non_mult_double_num),
    FUNC(test_change_diff_mult_null_json_to_non_non_mult_double_num),
    FUNC(test_change_equal_mult_str_json_to_non_non_mult_double_bool),
    FUNC(test_change_more_mult_str_json_to_non_non_mult_double_bool),
    FUNC(test_change_less_mult_str_json_to_non_non_mult_double_bool),
    FUNC(test_change_diff_mult_str_json_to_non_non_mult_double_bool),
    FUNC(test_change_equal_mult_num_json_to_non_non_mult_double_bool),
    FUNC(test_change_more_mult_num_json_to_non_non_mult_double_bool),
    FUNC(test_change_less_mult_num_json_to_non_non_mult_double_bool),
    FUNC(test_change_diff_mult_num_json_to_non_non_mult_double_bool),
    FUNC(test_change_equal_mult_bool_json_to_non_non_mult_double_bool),
    FUNC(test_change_more_mult_bool_json_to_non_non_mult_double_bool),
    FUNC(test_change_less_mult_bool_json_to_non_non_mult_double_bool),
    FUNC(test_change_diff_mult_bool_json_to_non_non_mult_double_bool),
    FUNC(test_change_equal_mult_null_json_to_non_non_mult_double_bool),
    FUNC(test_change_more_mult_null_json_to_non_non_mult_double_bool),
    FUNC(test_change_less_mult_null_json_to_non_non_mult_double_bool),
    FUNC(test_change_diff_mult_null_json_to_non_non_mult_double_bool),
    {NULL, NULL}};

static const struct TestChangeToMult PtrNonDoubleChangeToMult[] = {
    FUNC(test_change_single_str_json_to_ptr_non_single_double_num),
    FUNC(test_change_mult_str_json_to_ptr_non_single_double_num),
    FUNC(test_change_single_num_json_to_ptr_non_single_double_num),
    FUNC(test_change_mult_num_json_to_ptr_non_single_double_num),
    FUNC(test_change_single_bool_json_to_ptr_non_single_double_num),
    FUNC(test_change_mult_bool_json_to_ptr_non_single_double_num),
    FUNC(test_change_single_null_json_to_ptr_non_single_double_num),
    FUNC(test_change_mult_null_json_to_ptr_non_single_double_num),
    FUNC(test_change_single_str_json_to_ptr_non_single_double_bool),
    FUNC(test_change_mult_str_json_to_ptr_non_single_double_bool),
    FUNC(test_change_single_num_json_to_ptr_non_single_double_bool),
    FUNC(test_change_mult_num_json_to_ptr_non_single_double_bool),
    FUNC(test_change_single_bool_json_to_ptr_non_single_double_bool),
    FUNC(test_change_mult_bool_json_to_ptr_non_single_double_bool),
    FUNC(test_change_single_null_json_to_ptr_non_single_double_bool),
    FUNC(test_change_mult_null_json_to_ptr_non_single_double_bool),
    FUNC(test_change_equal_mult_str_json_to_ptr_non_mult_double_num),
    FUNC(test_change_more_mult_str_json_to_ptr_non_mult_double_num),
    FUNC(test_change_less_mult_str_json_to_ptr_non_mult_double_num),
    FUNC(test_change_diff_mult_str_json_to_ptr_non_mult_double_num),
    FUNC(test_change_equal_mult_num_json_to_ptr_non_mult_double_num),
    FUNC(test_change_more_mult_num_json_to_ptr_non_mult_double_num),
    FUNC(test_change_less_mult_num_json_to_ptr_non_mult_double_num),
    FUNC(test_change_diff_mult_num_json_to_ptr_non_mult_double_num),
    FUNC(test_change_equal_mult_bool_json_to_ptr_non_mult_double_num),
    FUNC(test_change_more_mult_bool_json_to_ptr_non_mult_double_num),
    FUNC(test_change_less_mult_bool_json_to_ptr_non_mult_double_num),
    FUNC(test_change_diff_mult_bool_json_to_ptr_non_mult_double_num),
    FUNC(test_change_equal_mult_null_json_to_ptr_non_mult_double_num),
    FUNC(test_change_more_mult_null_json_to_ptr_non_mult_double_num),
    FUNC(test_change_less_mult_null_json_to_ptr_non_mult_double_num),
    FUNC(test_change_diff_mult_null_json_to_ptr_non_mult_double_num),
    FUNC(test_change_equal_mult_str_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_more_mult_str_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_less_mult_str_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_diff_mult_str_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_equal_mult_num_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_more_mult_num_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_less_mult_num_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_diff_mult_num_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_equal_mult_bool_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_more_mult_bool_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_less_mult_bool_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_diff_mult_bool_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_equal_mult_null_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_more_mult_null_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_less_mult_null_json_to_ptr_non_mult_double_bool),
    FUNC(test_change_diff_mult_null_json_to_ptr_non_mult_double_bool),
    {NULL, NULL}};

static const struct TestChangeToMult NonArrDoubleChangeToMult[] = {
    FUNC(test_change_single_str_json_to_non_arr_single_double_num),
    FUNC(test_change_mult_str_json_to_non_arr_single_double_num),
    FUNC(test_change_single_num_json_to_non_arr_single_double_num),
    FUNC(test_change_mult_num_json_to_non_arr_single_double_num),
    FUNC(test_change_single_bool_json_to_non_arr_single_double_num),
    FUNC(test_change_mult_bool_json_to_non_arr_single_double_num),
    FUNC(test_change_single_null_json_to_non_arr_single_double_num),
    FUNC(test_change_mult_null_json_to_non_arr_single_double_num),
    FUNC(test_change_single_str_json_to_non_arr_single_double_bool),
    FUNC(test_change_mult_str_json_to_non_arr_single_double_bool),
    FUNC(test_change_single_num_json_to_non_arr_single_double_bool),
    FUNC(test_change_mult_num_json_to_non_arr_single_double_bool),
    FUNC(test_change_single_bool_json_to_non_arr_single_double_bool),
    FUNC(test_change_mult_bool_json_to_non_arr_single_double_bool),
    FUNC(test_change_single_null_json_to_non_arr_single_double_bool),
    FUNC(test_change_mult_null_json_to_non_arr_single_double_bool),
    FUNC(test_change_equal_mult_str_json_to_non_arr_mult_double_num),
    FUNC(test_change_more_mult_str_json_to_non_arr_mult_double_num),
    FUNC(test_change_less_mult_str_json_to_non_arr_mult_double_num),
    FUNC(test_change_diff_mult_str_json_to_non_arr_mult_double_num),
    FUNC(test_change_equal_mult_num_json_to_non_arr_mult_double_num),
    FUNC(test_change_more_mult_num_json_to_non_arr_mult_double_num),
    FUNC(test_change_less_mult_num_json_to_non_arr_mult_double_num),
    FUNC(test_change_diff_mult_num_json_to_non_arr_mult_double_num),
    FUNC(test_change_equal_mult_bool_json_to_non_arr_mult_double_num),
    FUNC(test_change_more_mult_bool_json_to_non_arr_mult_double_num),
    FUNC(test_change_less_mult_bool_json_to_non_arr_mult_double_num),
    FUNC(test_change_diff_mult_bool_json_to_non_arr_mult_double_num),
    FUNC(test_change_equal_mult_null_json_to_non_arr_mult_double_num),
    FUNC(test_change_more_mult_null_json_to_non_arr_mult_double_num),
    FUNC(test_change_less_mult_null_json_to_non_arr_mult_double_num),
    FUNC(test_change_diff_mult_null_json_to_non_arr_mult_double_num),
    FUNC(test_change_equal_mult_str_json_to_non_arr_mult_double_bool),
    FUNC(test_change_more_mult_str_json_to_non_arr_mult_double_bool),
    FUNC(test_change_less_mult_str_json_to_non_arr_mult_double_bool),
    FUNC(test_change_diff_mult_str_json_to_non_arr_mult_double_bool),
    FUNC(test_change_equal_mult_num_json_to_non_arr_mult_double_bool),
    FUNC(test_change_more_mult_num_json_to_non_arr_mult_double_bool),
    FUNC(test_change_less_mult_num_json_to_non_arr_mult_double_bool),
    FUNC(test_change_diff_mult_num_json_to_non_arr_mult_double_bool),
    FUNC(test_change_equal_mult_bool_json_to_non_arr_mult_double_bool),
    FUNC(test_change_more_mult_bool_json_to_non_arr_mult_double_bool),
    FUNC(test_change_less_mult_bool_json_to_non_arr_mult_double_bool),
    FUNC(test_change_diff_mult_bool_json_to_non_arr_mult_double_bool),
    FUNC(test_change_equal_mult_null_json_to_non_arr_mult_double_bool),
    FUNC(test_change_more_mult_null_json_to_non_arr_mult_double_bool),
    FUNC(test_change_less_mult_null_json_to_non_arr_mult_double_bool),
    FUNC(test_change_diff_mult_null_json_to_non_arr_mult_double_bool),
    {NULL, NULL}};

static const struct TestChangeToMult PtrArrDoubleChangeToMult[] = {
    FUNC(test_change_single_str_json_to_ptr_arr_single_double_num),
    FUNC(test_change_mult_str_json_to_ptr_arr_single_double_num),
    FUNC(test_change_single_num_json_to_ptr_arr_single_double_num),
    FUNC(test_change_mult_num_json_to_ptr_arr_single_double_num),
    FUNC(test_change_single_bool_json_to_ptr_arr_single_double_num),
    FUNC(test_change_mult_bool_json_to_ptr_arr_single_double_num),
    FUNC(test_change_single_null_json_to_ptr_arr_single_double_num),
    FUNC(test_change_mult_null_json_to_ptr_arr_single_double_num),
    FUNC(test_change_single_str_json_to_ptr_arr_single_double_bool),
    FUNC(test_change_mult_str_json_to_ptr_arr_single_double_bool),
    FUNC(test_change_single_num_json_to_ptr_arr_single_double_bool),
    FUNC(test_change_mult_num_json_to_ptr_arr_single_double_bool),
    FUNC(test_change_single_bool_json_to_ptr_arr_single_double_bool),
    FUNC(test_change_mult_bool_json_to_ptr_arr_single_double_bool),
    FUNC(test_change_single_null_json_to_ptr_arr_single_double_bool),
    FUNC(test_change_mult_null_json_to_ptr_arr_single_double_bool),
    FUNC(test_change_equal_mult_str_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_more_mult_str_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_less_mult_str_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_diff_mult_str_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_equal_mult_num_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_more_mult_num_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_less_mult_num_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_diff_mult_num_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_equal_mult_bool_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_more_mult_bool_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_less_mult_bool_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_diff_mult_bool_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_equal_mult_null_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_more_mult_null_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_less_mult_null_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_diff_mult_null_json_to_ptr_arr_mult_double_num),
    FUNC(test_change_equal_mult_str_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_more_mult_str_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_less_mult_str_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_diff_mult_str_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_equal_mult_num_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_more_mult_num_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_less_mult_num_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_diff_mult_num_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_equal_mult_bool_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_more_mult_bool_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_less_mult_bool_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_diff_mult_bool_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_equal_mult_null_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_more_mult_null_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_less_mult_null_json_to_ptr_arr_mult_double_bool),
    FUNC(test_change_diff_mult_null_json_to_ptr_arr_mult_double_bool),
    {NULL, NULL}};

#endif
